import { RarityKey } from './common'

export type WeaponTypeKey =
  | 'sword'
  | 'claymore'
  | 'polearm'
  | 'bow'
  | 'catalyst'

export const weaponSwordKeys = [
  'AmenomaKageuchi',
  'AquilaFavonia',
  'BlackcliffLongsword',
  'CinnabarSpindle',
  'CoolSteel',
  'DarkIronSword',
  'DullBlade',
  'FavoniusSword',
  'FesteringDesire',
  'FilletBlade',
  'FinaleOfTheDeep',
  'FleuveCendreFerryman',
  'FreedomSworn',
  'HaranGeppakuFutsu',
  'HarbingerOfDawn',
  'IronSting',
  'KagotsurubeIsshin',
  'KeyOfKhajNisut',
  'LightOfFoliarIncision',
  'LionsRoar',
  'MistsplitterReforged',
  'PrimordialJadeCutter',
  'PrototypeRancour',
  'RoyalLongsword',
  'SacrificialSword',
  'SapwoodBlade',
  'SilverSword',
  'SkyriderSword',
  'SkywardBlade',
  'SummitShaper',
  'SwordOfDescension',
  'TheAlleyFlash',
  'TheBlackSword',
  'TheFlute',
  'ToukabouShigure',
  'TravelersHandySword',
  'WolfFang',
  'XiphosMoonlight',
] as const
export type WeaponSwordKey = (typeof weaponSwordKeys)[number]

export const weaponClaymoreKeys = [
  'Akuoumaru',
  'BeaconOfTheReedSea',
  'BlackcliffSlasher',
  'BloodtaintedGreatsword',
  'DebateClub',
  'FavoniusGreatsword',
  'FerrousShadow',
  'ForestRegalia',
  'KatsuragikiriNagamasa',
  'LithicBlade',
  'LuxuriousSeaLord',
  'MailedFlower',
  'MakhairaAquamarine',
  'OldMercsPal',
  'PrototypeArchaic',
  'Rainslasher',
  'RedhornStonethresher',
  'RoyalGreatsword',
  'SacrificialGreatsword',
  'SerpentSpine',
  'SkyriderGreatsword',
  'SkywardPride',
  'SnowTombedStarsilver',
  'SongOfBrokenPines',
  'TalkingStick',
  'TheBell',
  'TheUnforged',
  'TidalShadow',
  'WasterGreatsword',
  'Whiteblind',
  'WhiteIronGreatsword',
  'WolfsGravestone',
] as const
export type WeaponClaymoreKey = (typeof weaponClaymoreKeys)[number]

export const weaponPolearmKeys = [
  'BalladOfTheFjords',
  'BeginnersProtector',
  'BlackcliffPole',
  'BlackTassel',
  'CalamityQueller',
  'CrescentPike',
  'Deathmatch',
  'DragonsBane',
  'DragonspineSpear',
  'EngulfingLightning',
  'FavoniusLance',
  'Halberd',
  'IronPoint',
  'KitainCrossSpear',
  'LithicSpear',
  'MissiveWindspear',
  'Moonpiercer',
  'PrimordialJadeWingedSpear',
  'PrototypeStarglitter',
  'RightfulReward',
  'RoyalSpear',
  'SkywardSpine',
  'StaffOfHoma',
  'StaffOfTheScarletSands',
  'TheCatch',
  'VortexVanquisher',
  'WavebreakersFin',
  'WhiteTassel',
] as const
export type WeaponPolearmKey = (typeof weaponPolearmKeys)[number]

export const weaponBowKeys = [
  'AlleyHunter',
  'AmosBow',
  'AquaSimulacra',
  'BlackcliffWarbow',
  'CompoundBow',
  'ElegyForTheEnd',
  'EndOfTheLine',
  'FadingTwilight',
  'FavoniusWarbow',
  'Hamayumi',
  'HuntersBow',
  'HuntersPath',
  'IbisPiercer',
  'KingsSquire',
  'Messenger',
  'MitternachtsWaltz',
  'MouunsMoon',
  'PolarStar',
  'Predator',
  'PrototypeCrescent',
  'RavenBow',
  'RecurveBow',
  'RoyalBow',
  'Rust',
  'SacrificialBow',
  'ScionOfTheBlazingSun',
  'SeasonedHuntersBow',
  'SharpshootersOath',
  'SkywardHarp',
  'Slingshot',
  'SongOfStillness',
  'TheFirstGreatMagic',
  'TheStringless',
  'TheViridescentHunt',
  'ThunderingPulse',
  'WindblumeOde',
] as const
export type WeaponBowKey = (typeof weaponBowKeys)[number]

export const weaponCatalystKeys = [
  'ApprenticesNotes',
  'AThousandFloatingDreams',
  'BlackcliffAgate',
  'DodocoTales',
  'EmeraldOrb',
  'EverlastingMoonglow',
  'EyeOfPerception',
  'FavoniusCodex',
  'FlowingPurity',
  'Frostbearer',
  'FruitOfFulfillment',
  'HakushinRing',
  'JadefallsSplendor',
  'KagurasVerity',
  'LostPrayerToTheSacredWinds',
  'MagicGuide',
  'MappaMare',
  'MemoryOfDust',
  'OathswornEye',
  'OtherworldlyStory',
  'PocketGrimoire',
  'PrototypeAmber',
  'QuantumCatalyst',
  'RoyalGrimoire',
  'SacrificialFragments',
  'SacrificialJade',
  'SkywardAtlas',
  'SolarPearl',
  'TheWidsith',
  'ThrillingTalesOfDragonSlayers',
  'TulaytullahsRemembrance',
  'TwinNephrite',
  'WanderingEvenstar',
  'WineAndSong',
] as const
export type WeaponCatalystKey = (typeof weaponCatalystKeys)[number]

export const weaponKeys = [
  ...weaponSwordKeys,
  ...weaponClaymoreKeys,
  ...weaponPolearmKeys,
  ...weaponBowKeys,
  ...weaponCatalystKeys,
] as const
export type WeaponKey = (typeof weaponKeys)[number]

export const weaponMaxLevel: Record<RarityKey, number> = {
  1: 70,
  2: 70,
  3: 90,
  4: 90,
  5: 90,
} as const

export const refinementKeys = [1, 2, 3, 4, 5] as const
export type RefinementKey = (typeof refinementKeys)[number]
